const seatSelectionsProps = {
  data: [
    [
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
      {price: 0, type: 'EMPTY_SPACE', ifBooked: true},
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
    ],
    [
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
      {price: 0, type: 'EMPTY_SPACE', ifBooked: true},
      {price: 0, type: 'SEAT', ifBooked: true},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
    ],
    [
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT', ifBooked: true},
      {price: 0, type: 'EMPTY_SPACE', ifBooked: true},
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
    ],
    [
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT', ifBooked: true},
      {price: 0, type: 'EMPTY_SPACE', ifBooked: true},
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
    ],
    [
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT', ifBooked: true},
      {price: 0, type: 'EMPTY_SPACE', ifBooked: true},
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
    ],
    [
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT', ifBooked: true},
      {price: 0, type: 'EMPTY_SPACE', ifBooked: true},
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
    ],
    [
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT', ifBooked: true},
      {price: 0, type: 'EMPTY_SPACE', ifBooked: true},
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
    ],
    [
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT', ifBooked: true},
      {price: 0, type: 'EMPTY_SPACE', ifBooked: true},
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
    ],
    [
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT', ifBooked: true},
      {price: 0, type: 'EMPTY_SPACE', ifBooked: true},
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
    ],
    [
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT', ifBooked: true},
      {price: 0, type: 'EMPTY_SPACE', ifBooked: true},
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
    ],
    [
      {price: 100, type: 'SEAT'},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT', ifBooked: true},
      {price: 0, type: 'EMPTY_SPACE', ifBooked: true},
      {price: 100, type: 'SEAT', selected: true},
      {price: 200, type: 'SEAT'},
      {price: 0, type: 'SEAT'},
    ],
  ],
};

export default seatSelectionsProps;
