const seatSelectionsProps = {
  onSeatPress: (seat) => {
    console.log('On seat select', seat);
    return {id: 123, fullName: 'Ravi Kumar'};
  },
  seatPassengerMap: {'1F': {id: 123, fullName: 'Ravi Kumar'}},
  activePassenger: {passengerId: 123, fullName: 'Ravi Kumar'},
  listColumns: ['A', 'B', 'C', null, 'D', 'E', 'F'],
  data: [
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#C3E1FF',
        isSeatAvailable: true,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#C3E1FF',
        isSeatAvailable: true,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#C3E1FF',
        isSeatAvailable: true,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#C3E1FF',
        isSeatAvailable: true,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: true,
      },
      {
        price: 999.0,
        code: '1F',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: true,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#C3E1FF',
        isSeatAvailable: true,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
    [
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {price: 0, type: 'AISLE'}, //isBooked
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
      {
        price: 999.0,
        code: '1A',
        type: 'SEAT',
        colorCode: '#F5F5F5',
        isSeatAvailable: false,
      },
    ],
  ],
};

export default seatSelectionsProps;
