const flightItineraryCardProps = {
  status: {
    key: 'PROCESSED',
    value: 'Processed',
    textColor: '#d65656',
    bgColor: '#d656561a',
  },
  tripRequest: {
    date: '22',
    month: 'Nov',
    year: '22',
    slotDetail: 'Slot: 6PM - 9PM',
    source: 'Delhi',
    destination: 'Mumbai',
    sourceAirportCode: 'BOM',
    destinationAirportCode: 'BLR',
    departureTime: '18:30',
    arrivalTime: '22:30',
    reduceOpacity: false,
    stop: 'Non stop (via Mumbai alskjdlakasdasdsjdlaskj)',
    airlineIcon:
      'https://storage.googleapis.com/fabm-test-uploader/airline_logo/SG.png',
    isPriceFetched: true,
    price: '₹2600',
    modificationCharge: '₹600',
    airlineCode: 'G8',
    flightNumber: '717',
    totalDuration: '1h 50min',
    airline: 'Indigo',
    isOutOfPolicy: true,
    modificationCharges: '₹300',
    isSoldOut: false,
  },
  bookingDetails: {
    flightBookingStatus: 'CONFIRMED',
    date: '22',
    month: 'Nov',
    year: '22',
    sourceAirportCode: 'BOM',
    destinationAirportCode: 'BLR',
    departureTime: '18:30',
    arrivalTime: '22:30',
    airlineCode: 'G8',
    flightNumber: '717',
    sourceAirportTerminal: 'Terminal 1',
    destinationAirportTerminal: 'Terminal 3',
    pnr: 'GBLP6Q',
    totalDuration: '1h 50min',
    airline: 'Indigo',
    stop: 'Non stop (via Hyderabad)',
    reduceOpacity: false,
    airlineIcon:
      'https://storage.googleapis.com/fabm-test-uploader/airline_logo/SG.png',
    isPriceFetched: true,
    price: '₹2600',
    // cancellationCharges: '₹600',
    // modificationCharges: '₹300',
    isOutOfPolicy: true,
  },

  remarks: {
    title: 'Modification remarks',
    text: 'Change of plans',
  },
  actions: [
    // {
    //   type: 'VIEW_REMARKS',
    //   name: 'Reschedule',
    // },
    {
      type: 'CANCEL',
      name: 'Cancel',
    },
    // {
    //   type: 'VIEW_REMARKS',
    // },
    // {
    //   type: 'SHORTLIST_FLIGHT_TRIPS',VIEW_SHORTLISTED_FLIGHT_TRIPS
    //   name: 'Flight shortlist ready',
    // },
    // {
    //   type: 'VIEW_SHORTLISTED_FLIGHT_TRIPS',
    //   name: 'Succefully shortlisted flights',
    // },
    // {
    //   type: 'REFUND_STATUS',
    //   name: 'Refund status',
    // },
  ],
  onActionPress: (item) => console.log('Action Pressed', item),
  onCardPress: (item) => console.log('Card Pressed', item),
  showLine: false,
  hideIcon: true,
  showInfo: false,
  isAlert: true,
  timelineGreyed: false,
  actionDisabled: true,
  showStatus: false,
  // notificationText: 'This is to notify something',
  showPreBookingCard: false,
  hideChevron: false,
};

export default flightItineraryCardProps;
