export const SubTripCommonActions = {
  VIEW_REMARKS: 'VIEW_REMARKS',
  SUPPORT: 'SUPPORT',
  CANCEL: 'CANCEL',
  RESCHEDULE: 'RESCHEDULE',
  EDIT: 'EDIT',
  REMOVE: 'REMOVE',
};

export const HotelSubTripActions = {
  ...SubTripCommonActions,
  DIRECTION: 'DIRECTION',
  PAY_NOW: 'PAY_NOW',
  MODIFY: 'MODIFY',
  SHORTLIST_HOTEL_TRIPS: 'SHORTLIST_HOTEL_TRIPS',
  VIEW_SHORTLISTED_HOTEL_TRIPS: 'VIEW_SHORTLISTED_HOTEL_TRIPS',
  VIEW_INVOICE: 'VIEW_INVOICE',
  SUBMIT_REVIEW: 'SUBMIT_REVIEW',
  SUBMIT_POS: 'SUBMIT_POS',
  MODIFICATION_REQUESTED: 'MODIFICATION_REQUESTED',
  CANCELLATION_REQUESTED: 'CANCELLATION_REQUESTED',
};

export const FlightSubTripActions = {
  ...SubTripCommonActions,
  SHORTLIST_FLIGHT_TRIPS: 'SHORTLIST_FLIGHT_TRIPS',
  VIEW_SHORTLISTED_FLIGHT_TRIPS: 'VIEW_SHORTLISTED_FLIGHT_TRIPS',
  MODIFICATION_REQUESTED: 'MODIFICATION_REQUESTED',
  CANCELLATION_REQUESTED: 'CANCELLATION_REQUESTED',
  REFUND_STATUS: 'REFUND_STATUS',
};

export const TrainSubtripActions = {
  ...SubTripCommonActions,
  SHORTLIST_TRAIN_TRIPS: 'SHORTLIST_TRAIN_TRIPS',
  VIEW_SHORTLISTED_TRAIN_TRIPS: 'VIEW_SHORTLISTED_TRAIN_TRIPS',
  MODIFICATION_REQUESTED: 'MODIFICATION_REQUESTED',
  CANCELLATION_REQUESTED: 'CANCELLATION_REQUESTED',
};

export const BusSubtripActions = {
  ...SubTripCommonActions,
  SHORTLIST_BUS_TRIPS: 'SHORTLIST_BUS_TRIPS',
  VIEW_SHORTLISTED_BUS_TRIPS: 'VIEW_SHORTLISTED_BUS_TRIPS',
  MODIFICATION_REQUESTED: 'MODIFICATION_REQUESTED',
  CANCELLATION_REQUESTED: 'CANCELLATION_REQUESTED',
};

export const CabSubtripActions = {
  ...SubTripCommonActions,
  SHORTLIST_CAB_TRIPS: 'SHORTLIST_CAB_TRIPS',
  VIEW_SHORTLISTED_CAB_TRIPS: 'VIEW_SHORTLISTED_CAB_TRIPS',
  MODIFICATION_REQUESTED: 'MODIFICATION_REQUESTED',
  CANCELLATION_REQUESTED: 'CANCELLATION_REQUESTED',
};
