export const HotelSubTripActions = {
  DIRECTION: 'DIRECTION',
  PAY_NOW: 'PAY_NOW',
  SUPPORT: 'SUPPORT',
  MODIFY: 'MODIFY',
  CANCEL: 'CANCEL',
  VIEW_REMARKS: 'VIEW_REMARKS',
  SHORTLIST_HOTEL_TRIPS: 'SHORTLIST_HOTEL_TRIPS',
  VIEW_SHORTLISTED_HOTEL_TRIPS: 'VIEW_SHORTLISTED_HOTEL_TRIPS',
  VIEW_INVOICE: 'VIEW_INVOICE',
  SUBMIT_REVIEW: 'SUBMIT_REVIEW',
  SUBMIT_POS: 'SUBMIT_POS',
};

export const FlightSubTripActions = {
  RESCHEDULE: 'RESCHEDULE',
  CANCEL: 'CANCEL',
  SUPPORT: 'SUPPORT',
  VIEW_REMARKS: 'VIEW_REMARKS',
  SHORTLIST_FLIGHT_TRIPS: 'SHORTLIST_FLIGHT_TRIPS',
  VIEW_SHORTLISTED_FLIGHT_TRIPS: 'VIEW_SHORTLISTED_FLIGHT_TRIPS',
};
