export default {
  add: 'Add',
  firstExpenseClaim: (date) => ` your first expense claim for ${date}`,
  actionNeeded: 'Action needed',
  contactSupport: 'Contact 24x7 Support',
  nothingInItineraryMsg: 'Nothing on your itinerary',
  reasonToProceed: 'Please enter a reason to proceed',
  support: 'Support',
  addAReceipt: 'Add a receipt',
  openCamera: 'Open camera',
  uploadFromGallery: 'Upload from gallery',
  importFromFiles: 'Import from files',
  clearAll: 'Clear all',
  filterExpenseType: 'Filter expense type',
  cancel: 'Cancel',
  apply: 'Apply',
  outOfPolicy: 'Out of policy',
  viewReceipt: ' View receipt',
  viewReceipts: (receiptCount) => ` View ${receiptCount} receipts`,
  claim: 'claim',
  uploadReceipt: 'Upload receipt',
  start: 'Start',
  stop: 'Stop',
  selectMonth: 'Select month',
  addAnother: 'Add another',
  upload: 'Upload',
  selectedFile: 'Selected file',
  kb: 'KB',
  addMore: 'Add more',
  uploadedReceipt: 'Uploaded receipt',
  stopsCount: (count) => `${count} stops`,
  helloUser: (profileName) => ` Hello, ${profileName}`,
  updates: 'Updates',
  seeMore: 'See more',
  approvalManager: 'Approval manager',
  cotravelerOptional: 'Co-travelers (optional)',
  coTravellerInfoText:
    'Same hotel and flight details as filled above shall be applicable to all travelers.',
  edit: 'Edit',
  slotInfo: (startTime, endTime) => `Slot: ${startTime} - ${endTime}`,
  addReturnFlight: 'Add return flight detail',
  flights: 'Flight(s)',
  hotels: 'Hotel(s)',
  returnDate: 'Return date',
  departureDate: 'Departure date',
  arrivalCity: 'Arrival city',
  departureCity: 'Departure city',
  basicTravelDetails: 'Enter basic travel details',
  sourcToDestination: (source, destination) => `${source} to ${destination}`,
  otherDetails: 'Other details',
  purposeOfTravel: 'Purpose of travel',
  otherRemarks: 'Other remarks (optional)',
  remove: 'Remove',
  itineraryNumber: (number) => `Itinerary ${number}`,
  coTravelerDetails: 'Co-traveler detail(s)',
  none: 'None',
  pnr: 'PNR',
  tapToSetPreference: (preference) =>
    `Tap to ${preference ? 'reset' : 'set'} preference`,
  depart: 'DEPART',
  return: 'RETURN',
  helpColleagueDecideNextTime: 'Help your colleague decide the next time',
  bookingId: 'Booking ID',
  directions: 'Directions',
  checkInDate: 'Check-in date',
  checkOutDate: 'Check-out date',
  checkInTime: (time) => `Check-in: ${time}`,
  checkOutTime: (time) => `Check-out: ${time}`,
  inclusions: 'Inclusions',
  rooms: 'Rooms',
  moreInclusions: (count) => ` +${count - 3} more`,
  coTravelers: 'Co-travelers',
  paymentMode: 'Payment mode',
  NA: 'N.A',
  viewDetails: (expanded) => `View ${expanded ? 'less' : 'more'} details`,
  starHotel: (starRating) => `${starRating} star hotel`,
  viewOnMap: 'View on map',
  your: 'Your',
  colleagueAvgRating: (rating) => ` colleagues rated it ${rating} (avg)`,
  requestBy: 'Request by: ',
  department: 'Department: ',
  designation: 'Designation: ',
  requestForModification: 'Request for modification',
  confirm: 'Confirm',
  approveRequest: 'Approve request',
  approve: 'Approve',
  rejectRequest: 'Reject request',
  reject: 'Reject',
  cotravelers: 'Co-traveler(s): ',
  remarks: 'Remarks',
  sort: 'Sort',
  filter: 'Filter',
  processing: 'Processsing',
  viewdetails: 'View details',
  addAStop: 'Add a stop',
  class: 'Class',
  preferredTrain: 'Preferred train',
  pickupTime: 'Pickup time: ',
  driverName: 'Driver Name',
  phoneNo: 'Phone no.',
  seatNumber: 'Seat no',
  coordinatorName: 'Coordinator Name',
  berth: 'Berth',
  platform: 'PF',
};
