export default {
  add: 'Add',
  firstExpenseClaim: (date) => ` your first expense claim for ${date}`,
  actionNeeded: 'Action needed',
  contactSupport: 'Contact 24x7 Support',
  nothingInItineraryMsg: 'Nothing on your itinerary',
  reasonToProceed: 'Please enter a reason to proceed',
  support: 'Support',
  addAReceipt: 'Add a receipt',
  openCamera: 'Open camera',
  uploadFromGallery: 'Upload from gallery',
  importFromFiles: 'Import from files',
  clearAll: 'Clear all',
  filterExpenseType: 'Filter expense type',
  cancel: 'Cancel',
  apply: 'Apply',
  outOfPolicy: 'Out of policy',
  viewReceipt: ' View receipt',
  viewReceipts: (receiptCount) => ` View ${receiptCount} receipts`,
  claim: 'claim',
  uploadReceipt: 'Upload receipt',
  start: 'Start',
  stop: 'Stop',
  selectMonth: 'Select month',
  addAnother: 'Add another',
  upload: 'Upload',
  selectedFile: 'Selected file',
  kb: 'KB',
  addMore: 'Add more',
  uploadedReceipt: 'Uploaded receipt',
  stopsCount: (count) => `${count} stops`,
  helloUser: (profileName) => ` Hello, ${profileName}`,
  updates: 'Updates',
  seeMore: 'See more',
};
